// This file is auto-generated by running `npx supabase gen types typescript`
// Update it after database schema changes

export type Database = {
  public: {
    Tables: {
      applications: {
        Row: {
          id: string
          user_id: string
          resume_url: string | null
          linkedin_post: string | null
          generated_email: string | null
          final_email: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          resume_url?: string | null
          linkedin_post?: string | null
          generated_email?: string | null
          final_email?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          resume_url?: string | null
          linkedin_post?: string | null
          generated_email?: string | null
          final_email?: string | null
          created_at?: string
        }
      }
    }
  }
}